# redis database url : http://127.0.0.1:8081/
#url: localhost:8081
#docker command: Inside Cricshop Terminal, docker-compose up --detach
#make sure docker desktop application is running

#stripe_website->docs->testing
#card numbers: VISA(Valid) -> 4242 4242 4242 4242
#3D-Auth Card: 4000 0027 6000 3184

#Tech stack of app: Angular, .Net, Typescript, c#, Sqlite, Redis, Docker, Stripe
services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - 8081:8081
    depends_on:
      - redis
    
volumes:
  redis-data: